### ISSUE TITLE
[Issue]: rocprofiler-sdk develop branch failing to compile in 7.1 container

### ISSUE THREAD

**Issue by cj401-amd** [ROCm/rocm-systems#1956]
### Problem Description

On ROCm-7.1.0, when building rocprofiler-sdk from develop branch,

```
/work/rocm-systems/projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hip/hip.cpp:153:32: error: cannot convert 'hipJitOption**' to 'hipJitOption*' in initialization
  153 |         _data_args = DataArgsT{args...};
      |                                ^~~~
      |                                |
      |                                hipJitOption**
/work/rocm-systems/projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hip/hip.cpp: In instantiation of 'static auto rocprofiler::hip::hip_api_impl<TableIdx, OpIdx>::set_data_args(DataArgsT&, Args ...) [with DataArgsT = rocprofiler_hip_api_args_t::<unnamed struct>; Args = {ihipLibrary_t**, const char*, hipJitOption**, void**, unsigned int, hipLibraryOption_e**, void**, unsigned int}; long unsigned int TableIdx = 1; long unsigned int OpIdx = 497]':
/work/rocm-systems/projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hip/hip.cpp:249:22:   required from 'static RetT rocprofiler::hip::hip_api_impl<TableIdx, OpIdx>::functor(Args ...) [with RetT = hipError_t; Args = {ihipLibrary_t**, const char*, hipJitOption**, void**, unsigned int, hipLibraryOption_e**, void**, unsigned int}; long unsigned int TableIdx = 1; long unsigned int OpIdx = 497]'
```
On ROCm-7.0.0, the building works. 

### Operating System

Ubuntu-22.04

### CPU

AMD EPYC 9354 32-Core Processor

### GPU

MI300

### ROCm Version

ROCm-7.1.0

**Comment by amd-ama10002-2** [comment]
I have also had troubles with build failure and I too see the same error, a signature mismatch for `hipLibraryLoadFromFile` between the ROCm 7.1.0 headers and the `rocprofiler-sdk` source.

### Root Cause Analysis (my best guess): 
The error occurs because the HIP runtime API in ROCm 7.1.0 uses **double-pointers** (`hipJitOption**` and `hipLibraryOption**`) for the option arguments, whereas the `rocprofiler-sdk` internal argument struct defines them as **single-pointers**.

1. **ROCm 7.1.0 Header Definition**
   In `/opt/rocm/include/hip/amd_detail/hip_prof_str.h` (and corresponding runtime headers), the signature expects double pointers:
   ```cpp
   // hipLibraryLoadFromFile[..., ('hipJitOption**', 'jitOptions'), ..., ('hipLibraryOption**', 'libraryOptions'), ...]
   ```

2. **rocprofiler-sdk Definition**
   In `projects/rocprofiler-sdk/source/include/rocprofiler-sdk/hip/api_args.h` (Commit: `2e0e6133`), the struct uses single pointers:
   ```cpp
   struct
   {
       hipLibrary_t*     library;
       const char*       fileName;
       hipJitOption*     jitOptions;        // <--- Mismatch: expects * but receives **
       void**            jitOptionsValues;
       unsigned int      numJitOptions;
       hipLibraryOption* libraryOptions;    // <--- Mismatch: expects * but receives **
       void**            libraryOptionValues;
       unsigned int      numLibraryOptions;
   } hipLibraryLoadFromFile;
   ```

3. **Compiler Context**
   We are building with strict type checking enabled via **Clang 18** (`-DCMAKE_CXX_COMPILER=clang++-18`). The compiler correctly refuses to initialize the single-pointer member variables with the double-pointer arguments provided by the HIP runtime callback:
   ```text
   error: cannot initialize a member subobject of type 'hipLibraryOption *' (aka 'hipLibraryOption_e *') with an lvalue of type 'hipLibraryOption_e **'
   ```

**Environment Details:**
*   **ROCm Version:** 7.1.0 (Build 7.1.0.70100-20~24.04)
*   **rocprofiler-sdk Commit:** `2e0e613397ccf89283e2e7f284d31a6b761d811d` (develop)
*   **Compiler:** Clang 18.*.*
*  **Dockerfile with based on rocm-7.1.x **: https://github.com/ROCm/unified-training-dockers/blob/4a1c52cda24c9869fdb049b1a68b60c8e7143ec5/jax_training/docker/Dockerfile
Here is the full Dockerfile if you cannot access the link:
<details>

```docker
ARG BASE_IMAGE=rocm/jax:rocm7.1-jax0.7.1-py3.12
FROM  ${BASE_IMAGE} AS jax_base

# Note: in the old base image has `ROCM_PATH` pointed to the wrong path.
# Need this to setup correctly for other components to build
ENV ROCM_PATH=/opt/rocm-7.1.0

# Note: in the old base image doesn't have /opt/rocm-7.1.0/bin added to PATH
ENV PATH="/opt/rocm-7.1.0/opencl/bin:/opt/rocm-7.1.0/bin:/opt/rocm-7.1.0/hcc/bin:/opt/rocm-7.1.0//bin:$PATH"

# Install LLVM 18
RUN echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main' | sudo tee /etc/apt/sources.list.d/llvm.list
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
RUN sudo apt-get update
RUN sudo apt-get install -y clang-18 lld-18 llvm-18-dev llvm-18-tools

RUN apt update \
    && apt install -y git \
    python3.12-venv \
    libdw1 \
    rocm-llvm-dev \
    libzstd-dev \
    libmsgpack-dev \
    libgtest-dev \
    libgmock-dev \
    libboost-filesystem-dev \
    gfortran \
    liblapack-dev \
    libblas-dev \
    libyaml-cpp-dev \
    pkg-config \
    libsqlite3-dev \
    libdw-dev \
    patchelf

# Setup python env
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip
RUN pip uninstall -y wheel \
    && pip install wheel==0.45.1
RUN pip install cmake==3.31.6 ninja==1.11.1.3

# amdsmi
RUN cd /opt/rocm/share/amd_smi \
    && pip install . \
    && cd -

# Rebuild rocprofiler-sdk
ARG ROCPROF_REPO=https://github.com/ROCm/rocm-systems.git
ARG ROCPROF_BRANCH=develop

RUN git clone --no-checkout --filter=blob:none ${ROCPROF_REPO} \
    && cd rocm-systems \
    && git sparse-checkout init --cone \
    && git sparse-checkout set projects/rocprofiler-sdk \
    && git checkout ${ROCPROF_BRANCH} \
    && cmake \
      -B rocprofiler-sdk-build \
      -DCMAKE_INSTALL_PREFIX=/opt/rocm \
      -DCMAKE_PREFIX_PATH=/opt/rocm \
      projects/rocprofiler-sdk \
    && cmake --build rocprofiler-sdk-build --target all --parallel $(nproc) \
    && cmake --build rocprofiler-sdk-build --target install \
    && cd .. \
    && rm -rf rocm-systems

# latest hipBLASLt
# Note: this might need to be installed before miopen
ARG HIPBLASLT_REPO=https://github.com/ROCm/rocm-libraries.git
ARG HIPBLASLT_BRANCH=2b7a409ab0975829b515d4280967c335391c0efd

ENV PYTORCH_ROCM_ARCH="gfx942;gfx950"
ENV Python_ROOT=/pyenv

RUN echo $(dpkg -l | awk '$2=="hipblaslt" { print $3 }') > ./OLD_HIPBLAST_VERSION
RUN git clone ${HIPBLASLT_REPO} \
    && cd rocm-libraries/projects/hipblaslt \
    && git checkout ${HIPBLASLT_BRANCH} \
    && python3 -m pip install -r tensilelite/requirements.txt \
    && wget -nv https://download.amd.com/developer/eula/aocl/aocl-4-2/aocl-linux-gcc-4.2.0_1_amd64.deb \
    && apt install ./aocl-linux-gcc-4.2.0_1_amd64.deb \
    && rm aocl-linux-gcc-4.2.0_1_amd64.deb \
    && dpkg --remove --force-depends hipblaslt hipblaslt-dev \
    && cmake --preset rocm-7.0.0 \
        -DGPU_TARGETS="${PYTORCH_ROCM_ARCH}" \
        -DCMAKE_PREFIX_PATH="${ROCM_PATH}/lib/llvm;${ROCM_PATH}" \
        -DCMAKE_INSTALL_PREFIX="${ROCM_PATH}" \
        -DCMAKE_PACKAGING_INSTALL_PREFIX="${ROCM_PATH}" \
        -DROCM_PATH="${ROCM_PATH}" \
        -B build -S. \
    && cmake --build build --target package --parallel \
    && dpkg -i build/*.deb \
    && cd ../../../ \
    && rm -rf rocm-libraries \
    && apt-get clean

# Link the latest hipblaslt with 0.x.x
# This is a workaround before pytorch officially supports hipblaslt 1.x.x
RUN sudo ln -s /opt/rocm/lib/libhipblaslt.so /opt/rocm/lib/libhipblaslt.so.0

# Fixes hipblaslt version in apt
RUN echo $(dpkg -l | awk '$2=="hipblaslt" { print $3 }') > ./NEW_HIPBLAST_VERSION
RUN sed -i -e "s/hipblaslt (= $(cat ./OLD_HIPBLAST_VERSION))/hipblaslt (= $(cat ./NEW_HIPBLAST_VERSION))/g" /var/lib/dpkg/status
RUN sed -i -e "s/hipblaslt-dev (= $(cat ./OLD_HIPBLAST_VERSION))/hipblaslt-dev (= $(cat ./NEW_HIPBLAST_VERSION))/g" /var/lib/dpkg/status
RUN rm OLD_HIPBLAST_VERSION NEW_HIPBLAST_VERSION

WORKDIR /workspace

# Install maxtext
ARG MAXTEXT_REPO=https://github.com/ROCm/maxtext.git
ARG MAXTEXT_BRANCH=genesu/add-jax-training-patches

RUN git clone ${MAXTEXT_REPO} \
    && cd maxtext \
    && git checkout ${MAXTEXT_BRANCH} \
    && chmod +x setup.sh \
    && find setup.sh -type f -print0 | xargs -0 sed -i 's/install_maxtext_github_deps//g' \
    && ./setup.sh \
    && cd ..

# Note: JAX and related libraries need to be installed before TE
# JAX
ENV ROCM_JAX_REPO=https://github.com/ROCm/rocm-jax.git
# This is the latest commit from rocm-jaxlib-v0.7.1 as of 11/10/2025
ENV ROCM_JAX_BRANCH=be6011b1b9d3e61e103fcf8700f54f9742d05fb5
ARG JAX_VERSION=0.7.1

# Note: The order is improtant here. If we install jax last, it will override the jaxlib in from
# the build. We need to install jax before building anything else.
RUN pip install jax==$JAX_VERSION

RUN pip uninstall -y jax-rocm7-plugin jax-rocm7-pjrt \
    && pip install patchelf \
    && git clone ${ROCM_JAX_REPO} \
    && cd rocm-jax \
    && git checkout ${ROCM_JAX_BRANCH} \
    && find stack.py -type f -print0 | xargs -0 sed -i "s/\$(shell rocminfo | grep -o -m 1 'gfx.*')/gfx942,gfx950/g" \
    && python3 stack.py develop --rebuild-makefile \
    && cd jax_rocm_plugin \
    && make install \
    && cd ../..

# TransformerEngine
ARG TE_REPO=https://github.com/ROCm/TransformerEngine.git
ARG TE_BRANCH=c95f9db61f2b2cc5ff86ba6c856a590c0428db25

WORKDIR /workspace

ENV USE_ROCM=1
ENV HIP_PATH=/opt/rocm
ENV NVTE_FRAMEWORK=jax
ENV CMAKE_BUILD_PARALLEL_LEVEL=64
ENV NVTE_ROCM_ARCH=${PYTORCH_ROCM_ARCH}
ENV NVTE_USE_ROCM=1
ENV NVTE_FUSED_ATTN_AOTRITON=0
ENV PYTHONPATH=/home/TransformerEngine/3rdparty/hipify_torch

RUN pip uninstall -y transformer_engine \
    && rm -rf TransformerEngine \
    && git clone --recursive ${TE_REPO} \
    && cd TransformerEngine \
    && git checkout ${TE_BRANCH} \
    && git submodule update --init --recursive \
    && python3 setup.py bdist_wheel 2>&1|tee pip_install.log \
    && pip install dist/*.whl \
    && cd .. \
    && pip show transformer_engine \
    && rm -rf TransformerEngine

# Configure required envs
ENV NVTE_ALLOW_NONDETERMINISTIC_ALGO=1
ENV NVTE_USE_HIPBLASLT=1
ENV GPU_MAX_HW_QUEUES=2
ENV HIP_FORCE_DEV_KERNARG=1
ENV HSA_FORCE_FINE_GRAIN_PCIE=1
ENV NVTE_FUSED_ATTN=1
ENV NCCL_DEBUG=VERSION
ENV NVTE_CK_USES_BWD_V3=1
ENV NVTE_CK_USES_FWD_V3=1
ENV NVTE_CK_IS_V3_ATOMIC_FP32=0
ENV NVTE_CK_HOW_V3_BF16_CVT=2
ENV NVTE_FUSED_ATTN_CK=1
ENV NVTE_FUSED_ATTN_AOTRITON=0
ENV XLA_PYTHON_CLIENT_MEM_FRACTION=.97
ENV XLA_FLAGS="--xla_gpu_memory_limit_slop_factor=95 --xla_gpu_reduce_scatter_combine_threshold_bytes=8589934592 --xla_gpu_enable_latency_hiding_scheduler=True --xla_gpu_all_gather_combine_threshold_bytes=8589934592 --xla_gpu_enable_triton_gemm=False --xla_gpu_enable_cublaslt=True --xla_gpu_autotune_level=0 --xla_gpu_enable_all_gather_combine_by_dim=FALSE"

# Revert maxtext to pull from upstream + apply patches
COPY jax_training/docker/google_forced_balance.patch /workspace/google_forced_balance.patch
COPY jax_training/docker/device-info.patch /workspace/device-info.patch
COPY jax_training/docker/max_to_keep.patch /workspace/max_to_keep.patch
COPY jax_training/docker/attention_mask.patch /workspace/attention_mask.patch
COPY jax_training/docker/quantization.patch /workspace/quantization.patch
COPY jax_training/docker/hf_data_processing.patch /workspace/hf_data_processing.patch
COPY jax_training/docker/CustomPackAndBatchOperation.py /workspace/CustomPackAndBatchOperation.py

RUN pip install flax==0.10.7 protobuf==6.31.1
RUN rm -rf maxtext \
    && git clone https://github.com/AI-Hypercomputer/maxtext.git \
    && cd maxtext \
    && git checkout 8def32a8a5b96fc6267636a8e58abfe4c178e161 \
    && patch -p1 < /workspace/google_forced_balance.patch \
    && patch -p1 < /workspace/device-info.patch \
    && patch -p1 < /workspace/max_to_keep.patch \
    && patch -p1 < /workspace/attention_mask.patch \
    && patch -p1 < /workspace/quantization.patch \
    && patch -p1 < /workspace/hf_data_processing.patch \
    && mv /workspace/CustomPackAndBatchOperation.py MaxText/input_pipeline/ \
    && cd ..

RUN rm /workspace/google_forced_balance.patch
RUN rm /workspace/device-info.patch
RUN rm /workspace/max_to_keep.patch
RUN rm /workspace/attention_mask.patch
RUN rm /workspace/quantization.patch
RUN rm /workspace/hf_data_processing.patch

# Note: jaxlib would be overridden by TE with the upstream version.
# Rebuild it here for rocm version
# Jaxlib
RUN pip uninstall -y jaxlib \
    && pip install patchelf \
    && cd rocm-jax \
    && python3 stack.py develop --rebuild-makefile \
    && cd jax_rocm_plugin \
    && make refresh_jaxlib \
    && cd /workspace \
    && rm -rf rocm-jax

# Clean up rocm-jax repo
RUN rm -rf /workspace/rocm-jax

# Clean cache
RUN rm -rf /root/.cache
```
</details>

You may need to add some additional cmake options to the dockerfile in order to force the use of clang-18 during the build. Here is an example of the options to use: 
<details>

```docker
RUN git clone --no-checkout --filter=blob:none ${ROCPROF_REPO} \
    && cd rocm-systems \
    && git sparse-checkout init --cone \
    && git sparse-checkout set projects/rocprofiler-sdk \
    && git checkout ${ROCPROF_BRANCH} \
    && cmake \
      -B rocprofiler-sdk-build \
      -DCMAKE_C_COMPILER=clang-18 \ # <-- This line is new
      -DCMAKE_CXX_COMPILER=clang++-18 \   # <-- This line is new 
      -DCMAKE_INSTALL_PREFIX=/opt/rocm \
      -DCMAKE_PREFIX_PATH=/opt/rocm \
      projects/rocprofiler-sdk \
    && cmake --build rocprofiler-sdk-build --target all --parallel $(nproc) \
    && cmake --build rocprofiler-sdk-build --target install \
    && cd .. \
    && rm -rf rocm-systems
```
If done correctly, then _I think_ you should see a line like this:
```bash
#16 7.170 -- The C compiler identification is Clang 18.1.8
#16 7.268 -- The CXX compiler identification is Clang 18.1.8
```
</details>

**Suggested Fix:**
To fix this, I think we either need:
- a rocprofiler-sdk tag/commit that matches ROCm 7.1’s HIP API, 
- or to build against a ROCm version that matches the hip-version_7.2... that rocprofiler-sdk develop expects.

**Comment by darren-amd** [comment]
Hi @cj401-amd,

Thanks for reporting this issue, I was able to reproduce it inside of a 7.1 container. This issue is appearing due to an ABI incompatibility between CLR in the 7.1 container and rocprofiler-sdk from the develop branch (specifically the double pointer vs pointer as highlighted above). This has since been fixed in: https://github.com/ROCm/rocm-systems/commit/27ec19116d00b32dae338947f555ea5eeafca18e, which will be included in the next release. In the meantime if you'd like to continue building from develop, please upgrade by following the instructions available [here](https://github.com/ROCm/rocm-systems/blob/develop/projects/clr/README-doc.md) and let me know if you run into any issues, thanks!

**Comment by darren-amd** [comment]
Hi @cj401-amd,

I verified that this issue is fixed on 7.1.1 that was released yesterday so going to close it out, thanks!
